Consistency in list-opening related exceptions.
MMListError: new base class for all list-opening related exceptions.

MMUnknownListError: Change to class-based exception inheriting from
MMListError.

MMBadListError: Becomes class MMCorruptListDatabaseError

MMListNotReady: Becomes class MMListNotReadyError

MMBadConfigError: removed.