StaleLockFileError: new exception to handle the case when a lock claimant crashes before cleaning up it's hardlink claim.
lock(): There's no reliable way to clean up stale hardlink lockfile
claims programmatically, so the best we can do is signal the error and
let a human fix the problem.  This happens when we've stolen the lock,
fail the 2-link test, but happen to be the lockfile winner.