True/False where appropriate.
Fixed the import of Stop, which was causing the import of this message
to fail.  The symptom was this traceback message in logs/error:

AttributeError: 'module' object has no attribute 'process'